#ifndef SRINTERFACE_GLOBAL_H
#define SRINTERFACE_GLOBAL_H

#if defined(SRINTERFACE_LIBRARY)
#  define SRINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SRINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif
#endif // SRINTERFACE_GLOBAL_H
